# Generated by Django 5.2.4 on 2026-02-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0002_alter_subcategory_options_amortizationschedule_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
