# Generated by Django 5.2.4 on 2026-02-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0003_remove_transaction_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='AccountTransaction',
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
