# Generated by Django 5.2.4 on 2026-02-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0004_rename_transaction_accounttransaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
