services:
  web:
    # Build the image using the Dockerfile in the current directory
    build:
      context: .
    
    # Mount the current directory into the container for live-reloading
    # Using :Z to handle SELinux permissions if you're on Linux
    volumes:
      - .:/app:Z
    
    # Environment variables for the Django application
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-6suv50cg&y26=*1zb1j_o$g4p7+5!=_tn#55@57%vi1&7!%^rd
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    
    # Mapping host port 9000 to container port 9000
    ports:
      - "8001:9000"
    
    # Command to run when the container starts
    # This will run migrations and then start the Django development server
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"]