# Generated by Django 5.0.2 on 2024-03-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_languages', to='settings.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_statuses', to='books.bookstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_types', to='books.booktype', verbose_name='Type'),
        ),
    ]
