# Generated by Django 5.0.2 on 2024-02-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_date_added_book_date_read_book_goodreads_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.bookgenre', verbose_name='Genre'),
        ),
    ]
