# Generated by Django 5.0.2 on 2024-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_language_alter_book_book_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goodreads_image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
