# Generated by Django 5.0.2 on 2024-03-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_goodreads_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='google_image_link',
        ),
    ]
