# Generated by Django 5.0.2 on 2024-02-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklanguage',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
