# Generated by Django 5.0.2 on 2024-03-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_logtype_logevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtype',
            name='user',
        ),
        migrations.DeleteModel(
            name='LogEvent',
        ),
        migrations.DeleteModel(
            name='LogType',
        ),
    ]
