# Generated by Django 5.0.2 on 2024-03-22 08:10

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_logtype_user_delete_logevent_delete_logtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload_to),
        ),
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload_to),
        ),
    ]
