# Generated by Django 5.0.2 on 2024-02-24 06:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import entertainment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('authors', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=entertainment.models.upload_to)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('published_date', models.DateField(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EntertainmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('related_field', models.CharField(choices=[('book_statuses', 'Book status'), ('book_genres', 'Book genre'), ('book_types', 'Book types'), ('book_languages', 'Book languages'), ('book_detail_currencies', 'Book details currencies'), ('game_statuses', 'Game status'), ('game_genres', 'Game genre'), ('game_detail_currencies', 'Game details currencies'), ('media_statuses', 'Media status'), ('media_genres', 'Media genre'), ('media_types', 'Media types')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_link', models.CharField(blank=True, max_length=255, null=True)),
                ('download_link', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='entertainment.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book_detail_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_detail_currencies', to='entertainment.entertainmentconfig', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Book detail',
                'verbose_name_plural': 'Book details',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='entertainment.entertainmentconfig', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_languages', to='entertainment.entertainmentconfig', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_statuses', to='entertainment.entertainmentconfig', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_types', to='entertainment.entertainmentconfig', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to=entertainment.models.upload_to)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('released_date', models.DateField(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('game_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_genres', to='entertainment.entertainmentconfig', verbose_name='Genre')),
                ('game_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses', to='entertainment.entertainmentconfig', verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_link', models.CharField(blank=True, max_length=255, null=True)),
                ('download_link', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_details', to='entertainment.game')),
                ('game_detail_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_detail_currencies', to='entertainment.entertainmentconfig', verbose_name='Currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game detail',
                'verbose_name_plural': 'Game details',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to=entertainment.models.upload_to)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('imdb_link', models.CharField(blank=True, max_length=255, null=True)),
                ('media_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_genres', to='entertainment.entertainmentconfig', verbose_name='Genre')),
                ('media_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_statuses', to='entertainment.entertainmentconfig', verbose_name='Status')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_types', to='entertainment.entertainmentconfig', verbose_name='Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='MediaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_link', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_details', to='entertainment.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media detail',
                'verbose_name_plural': 'Media details',
            },
        ),
    ]
