# Generated by Django 5.0.2 on 2024-03-11 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_steam_game_id_game_steam_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
