# Generated by Django 5.0.2 on 2024-03-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_steam_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='steam_image_link',
            new_name='game_image_link',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='steam_link',
            new_name='game_link',
        ),
    ]
