# Generated by Django 5.0.2 on 2024-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_link',
            new_name='movie_image_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
