# Generated by Django 5.0.2 on 2024-03-22 08:10

import main.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload_to),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload_to),
        ),
        migrations.AddField(
            model_name='moviestatus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload_to),
        ),
        migrations.AddField(
            model_name='movietype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.upload_to),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['movie_type'], name='movie_type_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['movie_genre'], name='movie_genre_idx'),
        ),
        migrations.AddIndex(
            model_name='moviedetail',
            index=models.Index(fields=['movie'], name='movie_idx'),
        ),
    ]
